version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins-i4gic_c
    volumes:
      - "D:/Learning/I4_GIC/S2/DevOps/storage/jenkins_home:/var/jenkins_home"
    links:
      - agent1
  agent1:
    build: ./laravel-agent
    image: i4c/laravel-agent:latest
    container_name: jenkins-laravel-agent-i4c
    environment:
      - JENKINS_URL=http://localhost:8080
      - JENKINS_AGENT_NAME=laravel-agent-I4c
      - "JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMwQZHLrGbGAnd6/YnP5TB3zMHepf0Mw25LEDk3pNS0h ADMIN@DESKTOP-J0KLTHC"
    volumes:
      - "D:/Learning/I4_GIC/S2/DevOps/storage/jenkins_agent_home:/var/jenkins_home"

  db:
    image: mysql:latest
    user: root
    container_name: jenkins-i4gic_c_db
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "D:/Learning/I4_GIC/S2/DevOps/storage/mysql:/var/lib/mysql"